### PR TITLE
Implement theme in App

### LINKED ISSUE #75: Create single file for theme related content
**Is your feature request related to a problem? Please describe.**
I would like to extract all colors, padding, margin, text size etc into single `theme.js`. This will help customize the styling of the app really straight forward, and client can modify the theme to reflect their brand style.

**Describe the solution you'd like**
1. Create [`colors.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/colors.js) to hold all colors used in app
2. Create [`spacing.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/spacing.js) that will hold standard spacing used for padding and margin.
3. Create [`typography.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/typography.js) to hold standard Text styles that can be reuse in entire app
4. Merge all `color`, `spacing`, `typography` into single [`theme.js`](https://github.com/alexakasanjeev/magento_react_native/blob/develop/src/theme/theme.js) which will be used by all component 

**Additional context**
I have implemented in my [magecart](https://github.com/alexakasanjeev/magento_react_native) repo, you can see it for reference.

### PR DESCRIPTION
**Pull request by alexakasanjeev**
**What does this implement/fix? Explain your changes.**
In entire app, `colors`, `typography` and values for `margin`/`padding`/`height`/`width` were defined in each component, which makes it hard to change. This PR introduce a `theme` module where all colors, typography and sizes are defined, so that only few changes in value can change the overall look of the app.

Major components are
- `colors.js` - where all colors used in entire app are defined
- `typography.js` - all typography related style are defined
- `spacing.js` - common padding/margin value defined
- `dimens.js` - component custom width/height are defined here
- `theme.js` - combine `colors.js`, `typography.js`, `spacing.js` & `dimens.js` into single module

**Does this close any currently open issues?**
close #75 

**Any other comments?**
Please read the guide how to use `theme` module at the end before merging pull request.

**Where has this been tested?**
---------------------------
 - Magento Version: [2.1.0]
 - Device: [Android Emulator Nexus 5X]
 - OS: [Android PIE]
 - Version [9.0 (Pie) - API 28]

---
# Guide: How to use theme module in the APP

## Access theme using react `Context` from Theme Module
Whenever you need to reference variables defined in `theme.js` in component do this

**For Functional Component**
```javascript
import React, { useContext } from 'react';
import { ThemeContext } from '../../theme';
//...
const CustomComponent = props => {
    const theme = useContext(ThemeContext);
    //...
    return <View style={{ backgroundColor: theme.colors.background }} />
}
```

**For Class Component**
```javascript
import React from 'react';
import { ThemeContext } from '../../theme';
//...
class CustomComponent  extends React.Component {
    static contextType = ThemeContext;
    //...
    render() {
        const theme = this.context;
        return <View style={{ backgroundColor: theme.colors.background }} />
   }
}
```

## To use typography from Theme Module
A custom `Text` component has been defined in `common` folder, which uses typography styles from `typography.js`. Use this `Text` component from common folder whenever you need to define text in any component

:heavy_check_mark: Use this in code
```javascript
import { Text } from '../common'; // import Text component from common folder
//...
    return (
       <View>
            <Text>Text which is theme aware</Text>
       </View>
    );
```

:x:  Don't do this
```javascript
import { Text } from 'react-native';
```

Also the `Text` component from `common` folder has various inbuilt font size available, don't define custom `fontSize` or `fontWeight` until and unless extremely needed
```javascript
<Text type="heading">This is a Heading</Text>
<Text type="subheading">This is a SubHeading</Text>
<Text type="body">This is a Body</Text>
<Text>Default is a Body</Text>
<Text type="label">This is a label</Text>
<Text type="caption">This is a caption</Text>
---
<Text type="heading" bold>This is a Bold Heading</Text>
<Text type="subheading" bold>This is a Bold SubHeading</Text>
<Text type="body" bold>This is a Bold Body</Text>
<Text type="label" bold>This is a Bold label</Text>
<Text type="caption" bold>This is a Bold caption</Text>
```

Screenshot_1570532238

## Colors used in Theme Module
Major colors are defined in `colors.js`, their use is also mention in this file, try to re-use colors from this file, don't define custom color until and unless absolutely needed.

| Color Name | Color Use |
|---|---|
| primaryDark | color for the status bar and for dark tint |
| primary | to be used as a background color for appbar(toolbar) |
| appBarTint | to be used for appbar title text, appbar icons color and for back button |
| secondaryLight | to be used for hover state |
| secondary| to be used as default button, checkbox, spinner, radio button and other component color |
| secondaryDark | to be used for active state |
| background | Any major Screen will have this as his default background color |
| surface | To be used as a default background for all components, like Card, CardSection, List etc |
| border | Use it for card border |
| success | Success messages and icons. |
| error | Error messages and icons. |

**Use**

```javascript
<View style={{ color: theme.colors.success }}
```
## Margin/Padding standard value used in Theme Module
To define value for margin or padding used values defined in `spacing.js`, try not to define custom padding value or margin in component

| Name | Size |
|---|---|
| tiny | 4 |
| small | 8 |
| medium | 12 |
| large | 16 |
| extraLarge | 24 |

:heavy_check_mark: Correct way of using

```javascript
<View style={{ padding: theme.spacing.large }}>
    <Text style={{ margin: theme.spacing.tiny }}>
```
:x: Wrong way

```javascript
<View style={{ padding: 16 }}>
    <Text style={{ margin: 4 }}>
```

## Component width/height and other values
Try to define component width, height, custom border radius in `dimens.js` file, and access this value from theme

**Use**
- Define property in dimens.js
```javascript
{
    customComponentHeight: 234,
    customComponentWidth: 345,
    //...
}
```
- In you `CustomComponent` access the property like
```javascript
const CustomComponent = props => {
    const theme = useContext(ThemeContext);
    //...
    return <Image style={{
        width: theme.dimens.customComponentWidth,
        height: theme.dimens.customComponentHeight,
    }}>
```

> And also I have mentioned in detail comments what each property do in their respective files,
> for example in `colors.js` I have mentioned where each color is supposed to be used, so if you need bigger pitcher, just read the comments in `colors.js`, `typography.js` etc

### CODE REVIEW

**Comment by alexakasanjeev** [comment]
**Screenshots**
Screenshot_1570529841
Screenshot_1570529846
Screenshot_1570529853
Screenshot_1570529869
Screenshot_1570534702

**Comment by troublediehard** [comment]
Huge work is done! @alexakasanjeev You are the man!

**Comment by alexakasanjeev** [comment]
Thank you so much Dmytro for accepting the contribution, sure would continue to contribute to the project.

I just want to thank you especially because I have learnt React Native because of your project, when I first started, I read your code and recreated the APP(magecart), by doing that I learnt how to build an actual high quality app. 

And this is my main reason for the contribution, so that other people(like I did) can come and learn React native from this project, we need project like this which are up to date and uses best practices. :smile:

**Comment by troublediehard** [comment]
It is actually my first React Native project, so I'm kind of smiling when looking at code now. But it is fine and people use it for real projects so still helpful.

**Comment by alexakasanjeev** [comment]
and did you understand the theme module and how the colors, typography, spacing and dimens are used, I have explained in the PR itself.

**Comment by troublediehard** [comment]
I haven't dive too deep, but I got the idea and I added it to the Readme.

**Comment by alexakasanjeev** [comment]
Yes just saw that, great, and if you need more context please do ask, 

and it is no way the only way of doing theme in APP, will continue to refine the theme module as I learn more.

**Pull request merged**
